def morse(word):
    if word == "A" or word == "a": return "10"
    if word == "B" or word == "b": return "0111"
    if word == "C" or word == "c": return "0101"
    if word == "D" or word == "d": return "011"
    if word == "E" or word == "e": return "1"
    if word == "F" or word == "f": return "1101"
    if word == "G" or word == "g": return "001"
    if word == "H" or word == "h": return "1111"
    if word == "I" or word == "i": return "11"
    if word == "J" or word == "j": return "1000"
    if word == "K" or word == "k": return "010"
    if word == "L" or word == "l": return "1011"
    if word == "M" or word == "m": return "00"
    if word == "N" or word == "n": return "01"
    if word == "O" or word == "o": return "000"
    if word == "P" or word == "p": return "1001"
    if word == "Q" or word == "q": return "0010"
    if word == "R" or word == "r": return "101"
    if word == "S" or word == "s": return "111"
    if word == "T" or word == "t": return "0"
    if word == "U" or word == "u": return "110"
    if word == "V" or word == "v": return "1110"
    if word == "W" or word == "w": return "100"
    if word == "X" or word == "x": return "0110"
    if word == "Y" or word == "y": return "0100"
    if word == "Z" or word == "z": return "0011"
    if word == "1": return "10000"
    if word == "2": return "11000"
    if word == "3": return "11100"
    if word == "4": return "11110"
    if word == "5": return "11111"
    if word == "6": return "01111"
    if word == "7": return "00111"
    if word == "8": return "00011"
    if word == "9": return "00001"
    if word == "0": return "00000"
    if word == " ": return " "
    if word == "`": return "`"
    if word == "~": return "~"
    if word == "!": return "!"
    if word == "@": return "@"
    if word == "#": return "#"
    if word == "$": return "$"
    if word == "%": return "%"
    if word == "^": return "^"
    if word == "&": return "&"
    if word == "*": return "*"
    if word == "(": return "("
    if word == "(": return ")"
    if word == "_": return "_"
    if word == "-": return "-"
    if word == "=": return "="
    if word == "+": return "+"
    if word == "|": return "|"
    if word == "/": return "/"
#    if word == ".": return "."
    if word == "?": return "?"
    if word == ">": return ">"
    if word == "<": return "<"
    if word == ",": return ","
    if word == "'": return "'"
    if word == ";": return ";"
    if word == ":": return ":"
    if word == "}": return "}"
    if word == "{": return "{"
    if word == "[": return "["
    if word == "]": return "]"
    if word == ":": return ":"
    if word == ";": return ";"




def demorse(word):
    if word == "10": return "A"
    if word == "0111": return "B"
    if word == "0101": return "C"
    if word == "011": return "D"
    if word == "1": return "E"
    if word == "1101": return "F"
    if word == "001": return "G"
    if word == "1111": return "H"
    if word == "11": return "I"
    if word == "1000": return "J"
    if word == "010": return "K"
    if word == "1011": return "L"
    if word == "00": return "M"
    if word == "01": return "N"
    if word == "000": return "O"
    if word == "1001": return "P"
    if word == "0010": return "Q"
    if word == "101": return "R"
    if word == "111": return "S"
    if word == "0": return "T"
    if word == "110": return "U"
    if word == "1110": return "V"
    if word == "100": return "W"
    if word == "0110": return "X"
    if word == "0100": return "Y"
    if word == "0011": return "Z"
    if word == "10000": return "1"
    if word == "11000": return "2"
    if word == "11100": return "3"
    if word == "11110": return "4"
    if word == "11111": return "5"
    if word == "01111": return "6"
    if word == "00111": return "7"
    if word == "00011": return "8"
    if word == "00001": return "9"
    if word == "00000": return "0"
    if word == " ": return " "
    if word == "`": return "`"
    if word == "~": return "~"
    if word == "!": return "!"
    if word == "@": return "@"
    if word == "#": return "#"
    if word == "$": return "$"
    if word == "%": return "%"
    if word == "^": return "^"
    if word == "&": return "&"
    if word == "*": return "*"
    if word == "(": return "("
    if word == "(": return ")"
    if word == "_": return "_"
    if word == "-": return "-"
    if word == "=": return "="
    if word == "+": return "+"
    if word == "|": return "|"
    if word == "/": return "/"
 #   if word == ".": return "."
    if word == "?": return "?"
    if word == ">": return ">"
    if word == "<": return "<"
    if word == ",": return ","
    if word == "'": return "'"
    if word == ";": return ";"
    if word == ":": return ":"
    if word == "}": return "}"
    if word == "{": return "{"
    if word == "[": return "["
    if word == "]": return "]"
    if word == ":": return ":"
    if word == ";": return ";"
